### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by burhanshakir** [udacity/ud120-projects#103]
When running nb_author_id.py, i get this in the logcat

Traceback (most recent call last):
  File "C:/Users/burha/PycharmProjects/ud120-projects/naive_bayes/nb_author_id.py", line 30, in <module>
    clf.fit(features_train, labels_train)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\naive_bayes.py", line 184, in fit
    sample_weight=sample_weight)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\sklearn\naive_bayes.py", line 341, in _partial_fit
    epsilon = 1e-9 * np.var(X, axis=0).max()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\core\fromnumeric.py", line 3146, in var
    **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\core\_methods.py", line 112, in _var
    x = asanyarray(arr - arrmean)
MemoryError

I am on Windows 10  64bit  core i5 8 gb ram.

How should I solve this ?

**Comment by aswells2** [comment]
You are running Python3.6-32. By default windows limits all x86 processes to 2GB of memory (https://msdn.microsoft.com/en-us/library/aa366778.aspx), so although your PC has plenty of processing capability, you are hamstrung by the 32bit version of Python. A workaround is to do what the tutorial suggests and decrease the size of the training set, but I would recommend installing Python36-64.

**Comment by krngd2** [comment]
I have Python3.6-64 but still showing the same error

**Comment by rikinp** [comment]
I am also facing the same error!
please upload the solution if anybody has it.

I am on Windows-7 64 bit i7 3rd gen and using python 2.7
