### ISSUE TITLE
19. Quiz GuassianNB Deployment

### ISSUE THREAD

**Issue by syedtalalarif** [udacity/ud120-projects#124]
Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_qleklyiyim/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_qleklyiyim/studentMain.py", line 13, in <module>
    from ClassifyNB import classify
  File "/tmp/vmuser_qleklyiyim/ClassifyNB.py", line 3
    from sklearn.naive_bayes import GuassianNB
       ^
IndentationError: expected an indented block

kindly help me in this
i am getting this error

**Comment by DTasev** [comment]
As the error says: check if your indenting is correct. If you're not sure, a quick google will help you. 

If it is, maybe try deleting the line and writing it again (if you copied from the sklearn website maybe it also copied an invisible utf8 character).

**Comment by iselind** [comment]
Make sure you stick to either tabs or spaces, don't mix them. Python is really picky when it comes to the indentation. Make sure the indentation is exactly the same as for the line before it you want your line to follow.
