### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by awaiseye** [udacity/ud120-projects#145]
I was trying to run np_author_id.py from spyder and this error occurred.

>  runfile('C:/Users/Awais/Downloads/ud120-projects-master/ud120-projects-master/naive_bayes/nb_author_id.py', wdir='C:/Users/Awais/Downloads/ud120-projects-master/ud120-projects-master/naive_bayes')
> Reloaded modules: email_preprocess
> Traceback (most recent call last):
> 
>   File "<ipython-input-24-0ed375423f7d>", line 1, in <module>
>     runfile('C:/Users/Awais/Downloads/ud120-projects-master/ud120-projects-master/naive_bayes/nb_author_id.py', wdir='C:/Users/Awais/Downloads/ud120-projects-master/ud120-projects-master/naive_bayes')
> 
>   File "C:\Users\Awais\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\Awais\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
>     exec(compile(scripttext, filename, 'exec'), glob, loc)
> 
>   File "C:/Users/Awais/Downloads/ud120-projects-master/ud120-projects-master/naive_bayes/nb_author_id.py", line 22, in <module>
>     features_train, features_test, labels_train, labels_test = preprocess()
> 
>   File "../tools/email_preprocess.py", line 59, in preprocess
>     features_test_transformed  = selector.transform(features_test_transformed).toarray()
> 
>   File "C:\Users\Awais\Anaconda2\lib\site-packages\scipy\sparse\compressed.py", line 964, in toarray
>     return self.tocoo(copy=False).toarray(order=order, out=out)
> 
>   File "C:\Users\Awais\Anaconda2\lib\site-packages\scipy\sparse\coo.py", line 252, in toarray
>     B = self._process_toarray_args(order, out)
> 
>   File "C:\Users\Awais\Anaconda2\lib\site-packages\scipy\sparse\base.py", line 1039, in _process_toarray_args
>     return np.zeros(self.shape, dtype=self.dtype, order=order)
> 
> MemoryError

I am running it from its original locaiton and as precaution I had already changed test_size = 0.5. But Still I am having this error. Please help

**Comment by LaloCo** [comment]
This happened to me, and what I did was install Python 64 bit and get rid of the 32-bit version, and just use 64 bit to run the code.

**Comment by claywong** [comment]
to get  larger memory

**Comment by KhinePisi** [comment]
or you can adjust test_size and analyze the results.
