### ISSUE TITLE
startup.py error?

### ISSUE THREAD

**Issue by vjaiwant99** [udacity/ud120-projects#156]
I'm getting the following issue :( while running startup.py
How to solve this?

Traceback (most recent call last):
File "startup.py", line 35, in
urllib.urlretrieve(url, filename="../enron_mail_20150507.tgz")
File "C:\Python27\lib\urllib.py", line 91, in urlretrieve
return _urlopener.retrieve(url, filename, reporthook, data)
File "C:\Python27\lib\urllib.py", line 237, in retrieve
fp = self.open(url, data)
File "C:\Python27\lib\urllib.py", line 205, in open
return getattr(self, name)(url)
File "C:\Python27\lib\urllib.py", line 435, in open_https
h.endheaders(data)
File "C:\Python27\lib\httplib.py", line 951, in endheaders
self._send_output(message_body)
File "C:\Python27\lib\httplib.py", line 811, in _send_output
self.send(msg)
File "C:\Python27\lib\httplib.py", line 773, in send
self.connect()
File "C:\Python27\lib\httplib.py", line 1158, in connect
self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
File "C:\Python27\lib\ssl.py", line 372, in wrap_socket
ciphers=ciphers)
File "C:\Python27\lib\ssl.py", line 134, in init
self.do_handshake()
File "C:\Python27\lib\ssl.py", line 296, in do_handshake
self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 1] _ssl.c:503: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by surana-mudit** [comment]
Hey @vjaiwant99 , did you get the solution to your problem, actually i am also facing the same error

**Comment by MedAmr** [comment]
how long does it takes to download all the files? im waiting since 30 mn and didnt finish yet...
