### ISSUE TITLE
GaussianNB Deployment Beginner Issue

### ISSUE THREAD

**Issue by schls** [udacity/ud120-projects#176]
Hello, 
I have a question concerning the first programming quiz. As i am completely new to python i am struggling to complete the assignment. 

I added the code lines ClassifyNB.py:

from sklearn.naive_bayes import GaussianNB
    clf = GaussianNB()
    clf.fit(features_train, labels_train)

Am I missing something?
These are the error messages that i get:

Traceback (most recent call last): File "vm_main.py", line 33, in <module> 
import main 
File "/tmp/vmuser_eyiyyehtbu/main.py", line 2, in <module> 
import studentMain 
File "/tmp/vmuser_eyiyyehtbu/studentMain.py", line 37, in <module> 
prettyPicture(clf, features_test, labels_test) 
File "/tmp/vmuser_eyiyyehtbu/class_vis.py", line 26, in 
prettyPicture Z = clf.predict(np.c_[xx.ravel(), yy.ravel()]) 
AttributeError: 'NoneType' object has no attribute 'predict'

by quickly googling it, I figured that the AttributeError means that the assignment or function that i am calling up failed/ returned an unexpected result.

I would appreciate any help and recommendations
Thank you in advance.

**Comment by Mathanraj-Sharma** [comment]
`import sys
from time import time
sys.path.append("../tools/")
from email_preprocess import preprocess
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics


### features_train and features_test are the features for the training
### and testing datasets, respectively
### labels_train and labels_test are the corresponding item labels
features_train, features_test, labels_train, labels_test = preprocess()

#########################################################
### your code goes here ###
model = GaussianNB()
model.fit(features_train, labels_train)
predict = model.predict(features_test)

print("Accuracy: ",metrics.accuracy_score(labels_test,predict))`
