### ISSUE TITLE
startup.py - No such file or directory. 

### ISSUE THREAD

**Issue by aalfaroiii** [udacity/ud120-projects#179]
Hi, I have been trying to solve this on my own for the past 3 days wth no luck. If anyone can lend me a hand it will be terrific. Thanks in advance. 

#!/usr/bin/python

print
print "checking for nltk"
try:
    import nltk
except ImportError:
    print "you should install nltk before continuing"

print "checking for numpy"
try:
    import numpy
except ImportError:
    print "you should install numpy before continuing"

print "checking for scipy"
try:
    import scipy
except:
    print "you should install scipy before continuing"

print "checking for sklearn"
try:
    import sklearn
except:
    print "you should install sklearn before continuing"

print
print "downloading the Enron dataset (this may take a while)"
print "to check on progress, you can cd up one level, then execute <ls -lthr>"
print "Enron dataset should be last item on the list, along with its current size"
print "download will complete at about 423 MB"
import urllib
url = "https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tar.gz"
urllib.urlretrieve(url, filename="./enron_mail_20150507.tar.gz") 
print "download complete!"

print
print "unzipping Enron dataset (this may take a while)"
import tarfile
import os
os.chdir("..")
tfile = tarfile.open("../enron_mail_20150507.tar.gz", "r:gz")
tfile.extractall(".")

print "you're ready to go!"

------------------------------------------------------------------------------------------------------

> system("python env/ud120-projects/tools/startup.py")

checking for nltk
you should install nltk before continuing
checking for numpy
checking for scipy
checking for sklearn
you should install sklearn before continuing

downloading the Enron dataset (this may take a while)
to check on progress, you can cd up one level, then execute <ls -lthr>
Enron dataset should be last item on the list, along with its current size
download will complete at about 423 MB
download complete!

unzipping Enron dataset (this may take a while)
Traceback (most recent call last):
  File "env/ud120-projects/tools/startup.py", line 44, in <module>
    tfile = tarfile.open("../enron_mail_20150507.tar.gz", "r:gz")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1685, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1732, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '../enron_mail_20150507.tar.gz'

**Comment by tcdat96** [comment]
have you tried removing "./" in the **tarfile.open**
```
tfile = tarfile.open("enron_mail_20150507.tar.gz", "r:gz")
```
