### ISSUE TITLE
getting str error

### ISSUE THREAD

**Issue by vinayeq** [udacity/ud120-projects#194]
TypeError                                 Traceback (most recent call last)
<ipython-input-2-094ccc29a347> in <module>()
----> 1 import outlier_removal_regression

~\outlier_removal_regression.py in <module>()
     10 
     11 ### load up some practice data with outliers in it
---> 12 ages = pickle.load( open("practice_outliers_ages.pkl", "r") )
     13 net_worths = pickle.load( open("practice_outliers_net_worths.pkl", "r") )
     14 

TypeError: a bytes-like object is required, not 'str'

**Comment by DreaMer963** [comment]
> The reason for this error is that in Python 3, strings are Unicode, but when transmitting on the network, the data needs to be bytes strings instead.
> In pickle.load function, the parameter "r" should be replaced with "rb".
> like this ,
> ` ages = pickle.load( open("practice_outliers_ages.pkl", "rb") )`
> `net_worths = pickle.load( open("practice_outliers_net_worths.pkl", "rb") )`

then a issues will happen:
UnpicklingError: the STRING opcode argument must be quoted

**Comment by Shinshan1930** [comment]
No directory found word_data_unix.pkl 
  File "F:/github/ud120-projects/decision_tree/dt_author_id.py", line 20, in <module>
    features_train, features_test, labels_train, labels_test = preprocess()
  File "F:\github\ud120-projects\decision_tree\email_preprocess.py", line 36, in preprocess
    words_file_handler = open(words_file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../tools/word_data_unix.pkl'

Process finished with exit code 1

**Comment by waiyankyaw961999** [comment]
I got the same issues saying
                                                                 File "nb_author_id.py", line 10, in
 <module>
    features_train, features_test, labels_train, labels_test = preprocess()
  File "C:\Users\Wai Yan Kyaw\PycharmProjects\AWS Machine Learning Foundation\email_preprocess.py", l
ine 35, in preprocess
    word_data = pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: the STRING opcode argument must be quoted

**Comment by jaimep01** [comment]
Hello every1 in Win10 this fixed it:
Remember when openning the file as well it has to be read as bytes:

    authors_file_handler = open(authors_file, "rb")
    words_file_handler = open(words_file, "rb")

PowerShell:
$path = "\word_data.pkl"
(Get-Content $path -Raw).Replace("rn","`n") | Set-Content $path -Force

(add you whole path to avoid issues)

**Comment by fadimaximos** [comment]
This is for Win10
My solution was to was just to add the whole path from my PC to the `joblib.load` command.
Remember to change `/` to `\\`
