### ISSUE TITLE
startup.py error

### ISSUE THREAD

**Issue by kartik2206** [udacity/ud120-projects#199]
Running `startup.py` file is giving the below error
`Traceback (most recent call last):
  File "F:\Anaconda3\envs\py27\lib\runpy.py", line 182, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "F:\Anaconda3\envs\py27\lib\runpy.py", line 107, in _get_module_details
    raise error(format(e))
ImportError: No module named module`

I am using Anaconda python 2.7 interpretor inside VS code. What should I do to solve this problem ?

**Comment by akshaykumaru18** [comment]
just use terminal and python startup.py to run..
Anaconda is not necessary for running this file..
