### ISSUE TITLE
Download Link is deprecated in startup.py

### ISSUE THREAD

**Issue by augustolf** [udacity/ud120-projects#225]
I`m trying to run the startup.py and I got the following error:

(ud120) c:\Users\augustolf\My Documents\udacity\ud120-projects\tools>python startup.py

checking for nltk
checking for numpy
checking for scipy
checking for sklearn

downloading the Enron dataset (this may take a while)
to check on progress, you can cd up one level, then execute <ls -lthr>
Enron dataset should be last item on the list, along with its current size
download will complete at about 423 MB
Traceback (most recent call last):
  File "startup.py", line 35, in <module>
    urllib.urlretrieve(url, filename="../enron_mail_20150507.tar.gz")
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "C:\Users\augustolf\Anaconda3\envs\ud120\lib\socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by haiderah** [comment]
good morning brother I ran into many issues that you probably will run into as well,
this error because you probably have a poor connection
so go to the website and download an unzip it manually and everything shall work fine.
and this is the link
https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tar.gz

make sure you download and unzip at the same directory of the uda120project 
and if you use python 3x instead of python 2x you will run into few problems that are easy to solve 
feel free to reach me out anytime you need.

**Comment by akshaykumaru18** [comment]
Well for me i did not get any issues while running but which i faced was enron_dataset was downloading whole day
**startup.py** takes 1 full day to download , unzip and finish the process....

**Comment by mani818686** [comment]
> Well for me i did not get any issues while running but which i faced was enron_dataset was downloading whole day
> **startup.py** takes 1 full day to download , unzip and finish the process....
what i have to do if i want to do project
i extracted the above file
