### ISSUE TITLE
ImportError: cannot import name cross_validation

### ISSUE THREAD

**Issue by moha1313128** [udacity/ud120-projects#252]
Traceback (most recent call last):
  File "nb_author_id.py", line 19, in <module>
    from email_preprocess import preprocess
  File "../tools/email_preprocess.py", line 7, in <module>
    from sklearn import cross_validation
ImportError: cannot import name cross_validation

**Comment by Tinsae-Tadesse** [comment]
Hello @moha1313128 ,
Check [this](https://github.com/udacity/ud120-projects/issues/200) solution:
