### ISSUE TITLE
ValueError: Expected 2D array, got scalar array instead:

### ISSUE THREAD

**Issue by shail1612** [udacity/ud120-projects#254]
Traceback (most recent call last):

  File "<ipython-input-12-6f0e336debd7>", line 11, in <module>
    features_train, features_test, labels_train, labels_test = preprocess()

  File "C:\Users\shaijais\AppData\Local\Programs\Git\ud120-projects\tools\email_preprocess.py", line 50, in preprocess
    features_train_transformed = vectorizer.fit_transform(features_train).reshape(-1,1)

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 1863, in fit_transform
    return self._tfidf.transform(X, copy=False)

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py", line 1516, in transform
    X = normalize(X, norm=self.norm, copy=False)

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_data.py", line 1705, in normalize
    estimator='the normalize function', dtype=FLOAT_DTYPES)

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 549, in check_array
    "if it contains a single sample.".format(array))

**Comment by shanaya5855** [comment]
Try this syntax:
**model.predict([[variables]])**

Eg: 
reg=linear_model.LinearRegression()
reg.fit(x,y)
reg.predict([[100]])

This should work.

**Comment by amanmishra7ave** [comment]
thanks it worked
