### ISSUE TITLE
nltk doesn't support python 2.7

### ISSUE THREAD

**Issue by pavanvemana** [udacity/ud120-projects#280]
When I am trying to run ``python startup.py`` I am getting the following error

``
File "startup.py", line 6, in <module>
    import nltk
  File "/Users/vemana.teja/.pyenv/versions/ml/lib/python2.7/site-packages/nltk/__init__.py", line 128, in <module>
    from nltk.collocations import *
  File "/Users/vemana.teja/.pyenv/versions/ml/lib/python2.7/site-packages/nltk/collocations.py", line 35, in <module>
    from nltk.probability import FreqDist
  File "/Users/vemana.teja/.pyenv/versions/ml/lib/python2.7/site-packages/nltk/probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
``

**Comment by chrisdraws** [comment]
same issue here

**Comment by pavanvemana** [comment]
@chrisdraws I have changed `startup.py` to support python 3 and was able to get things going for now. But, eventually this repo needs to be updated to support **python3**.

**Comment by chrisdraws** [comment]
Thank you for the reply!! How do I get the updated version of startup.py?
I don't see it in github, it still looks like the old version from 3 years
ago.  Thanks I really appreciate your help!

**Comment by digicom1978** [comment]
Hi, I'm using Python 2.7 and installed nltk. (Its version is 3.x)
Then when I run startup.py, it has an issue of syntax error like below.

----------------------------------------------------------------------------------
checking for nltk
Traceback (most recent call last):
  File "startup.py", line 6, in <module>
    import nltk
  File "C:\Python27\lib\site-packages\nltk\__init__.py", line 128, in <module>
    from nltk.collocations import *
  File "C:\Python27\lib\site-packages\nltk\collocations.py", line 35, in <module>
    from nltk.probability import FreqDist
  File "C:\Python27\lib\site-packages\nltk\probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
                                          ^
SyntaxError: invalid syntax
----------------------------------------------------------------------------------

It seems it is because nltk is using python 3 instead of python 2.

What can I do for this?
Do I need to convert scripts to run in python 3?

Thank you in advance.

**Comment by pavanvemana** [comment]
`#!/usr/bin/python

print()
print("checking for nltk")
try:
    import nltk
except ImportError:
    print("you should install nltk before continuing")

print ("checking for numpy")
try:
    import numpy
except ImportError:
    print ("you should install numpy before continuing")

print("checking for scipy")
try:
    import scipy
except:
    print( "you should install scipy before continuing")

try:
    import sklearn
except:
    print( "you should install sklearn before continuing")

print()
print ("downloading the Enron dataset (this may take a while)")
print ("to check on progress, you can cd up one level, then execute <ls -lthr>")
print( "Enron dataset should be last item on the list, along with its current size")
print ("download will complete at about 423 MB")
from urllib.request import urlretrieve
url = "https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tar.gz"
urlretrieve(url, filename="../enron_mail_20150507.tar.gz") 
print("download complete!")


print()
print ("unzipping Enron dataset (this may take a while)")
import tarfile
import os
os.chdir("..")
tfile = tarfile.open("enron_mail_20150507.tar.gz", "r:gz")
tfile.extractall(".")

print("you're ready to go!")`

You can update `startup.py` with this which runs in python3. There may be additional changes required in other modules as you go forward in the course.

**Comment by digicom1978** [comment]
Thank you pavanvemana.
I started converting script fitting into Python3.

**Comment by PreetPRG** [comment]
@pavanvemana  I am having the same issue, tried your solution to convert startup.py as u had shown. But problem persists. And i guess the problem is with nltk lib not with startup.py file.

**Comment by pavanvemana** [comment]
@PreetPRG  Can you elaborate ? What error do you see ?

**Comment by PreetPRG** [comment]
@pavanvemana I have solved it. But my point was support for nltk is not provided in python 2, to use NLTK one requires to install python3

**Comment by pavanvemana** [comment]
@PreetPRG  That's exactly why opened the issue.

**Comment by ViAsmit** [comment]
I was also having the same problem.
Do the following steps:
1. Open Terminal
2. make sure you have pip install for python2
3. Move to the directory where you have cloned this repository.
4. Run this command: `pip install -r requirements.txt`
5. All modules will successfully install.

Hop I helped :)

If it doesn't work, Do let me know.
