### ISSUE TITLE
Unable to download from the URL

### ISSUE THREAD

**Issue by Volpone24** [udacity/ud120-projects#286]
downloading the Enron dataset (this may take a while)
to check on progress, you can cd up one level, then execute <ls -lthr>
Enron dataset should be last item on the list, along with its current size
download will complete at about 423 MB
Traceback (most recent call last):
  File "e:/College/ML/ud120-projects/tools/startup.py", line 35, in <module>
    urllib.urlretrieve(url, filename="../enron_mail_20150507.tar.gz")
  File "C:\Python27\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Python27\lib\urllib.py", line 251, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 13] Permission denied: '../enron_mail_20150507.tar.gz'

**Comment by nC3rtainity** [comment]
Find the data set here. https://zoo.cs.yale.edu/classes/cs458/lectures/sklearn/ud/ud120-projects-master/

**Comment by cassiasamp** [comment]
I'm having the same problem, what I did was fix the startup.py file. Is is okay if I contribute with it so we could close this issue?

**Comment by sinhashivam0807** [comment]
https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tar.gz navigate through this.
Once downloaded you can can save it directly inside folder ud120-projects.

**Comment by HanySElhady** [comment]
once downloaded to the path should i extract it or not?

**Comment by gramdharey** [comment]
> once downloaded to the path should i extract it or not?

Were you able to extract it?

**Comment by gramdharey** [comment]
> once downloaded to the path should i extract it or not?

Were you able to extract it?

**Comment by Gyan313** [comment]
> > once downloaded to the path should i extract it or not?
> 
> Were you able to extract it?

Bro, did you extract the dataset after downloading cause i am using jupyter notebook and after extracting the dataset , a folder is created named `maildir` but inside that folder there is no data. Did you faced the same problem ? Can you help me......😢

**Comment by gramdharey** [comment]
> > > once downloaded to the path should i extract it or not?
> > 
> > Were you able to extract it?
> 
> Bro, did you extract the dataset after downloading cause i am using jupyter notebook and after extracting the dataset , a folder is created named `maildir` but inside that folder there is no data. Did you faced the same problem ? Can you help me......😢
> 

I actually can't remember this aspect, but I guess I didn't face this issue. If u find it difficult,  I guess some people might have the file folder directly where the dataset is. Thanks
