### ISSUE TITLE
tarfile is not able to extract Enron dataset

### ISSUE THREAD

**Issue by pg30** [udacity/ud120-projects#310]
In lesson 1, after running startup.py and downloading it, it gives the following error

> IOError: [Errno 22] invalid mode ('wb') or filename: './maildir/blair-l/personnel___promotions/1.'

I think this is because the files are ending with a dot.

**Comment by MedAmr** [comment]
can you post a whole screenshot of your issue?

**Comment by pg30** [comment]
Sure, This is what happens when i run startup.py after the file is downloaded.

```
checking for nltk
checking for numpy
checking for scipy
checking for sklearn
unzipping Enron dataset (this may take a while)
Traceback (most recent call last):

  File "/media/pranay/PG/PRANAY/udacity courses/Intro to machine learning/ud120-projects/tools/startup.py", line 45, in <module>
    tfile.extractall(".")

  File "/home/pranay/anaconda3/lib/python3.8/tarfile.py", line 2024, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),

  File "/home/pranay/anaconda3/lib/python3.8/tarfile.py", line 2065, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),

  File "/home/pranay/anaconda3/lib/python3.8/tarfile.py", line 2137, in _extract_member
    self.makefile(tarinfo, targetpath)

  File "/home/pranay/anaconda3/lib/python3.8/tarfile.py", line 2178, in makefile
    with bltn_open(targetpath, "wb") as target:

OSError: [Errno 22] Invalid argument: './maildir/blair-l/personnel___promotions/1.'
```

**Comment by pg30** [comment]
Basically according to me the problem is in the filenames ending with dot (like 1. , 2.) because i renamed (1. to 1) and when extracted that single file, it got extracted successfully except for others with dot but this is impossible to do for all the files.
I am running ubuntu 20.04

**Comment by trsvchn** [comment]
Hi! @pg30 I've ported this ud120 code to `python3.8` and `jupyter`, I've reorganized most of components (e.g. startup script) and fixed some issues. Fell free to take a look at my fork [trsvchn/ud120-projects-py3-jupyter](https://github.com/trsvchn/ud120-projects-py3-jupyter).

**Comment by olabod67** [comment]
Hi,
Can someone assist with the problem I'm having running startup.py?
I'm currently running it on python 3.8 and find the screen shot of the error message below:

checking for nltk
checking for numpy
checking for scipy
checking for sklearn
downloading the Enron dataset (this may take a while)
to check on progress, you can cd up one level, then execute <ls -lthr>
Enron dataset should be last item on the list, along with its current size
download will complete at about 423 MB
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-68548ac1bc8f> in <module>
     33 import urllib
     34 url = "https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tar.gz"
---> 35 urllib.urlretrieve(url, filename="../enron_mail_20150507.tar.gz")
     36 print("download complete!")
     37 

AttributeError: module 'urllib' has no attribute 'urlretrieve'

**Comment by olabod67** [comment]
Please, I need the community assistance on this. Can you help?
