### ISSUE TITLE
Can't start the nb_author_id

### ISSUE THREAD

**Issue by MedAmr** [udacity/ud120-projects#311]
hi everyone,
did anyone had this kind of error:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 17, in <mod
ule>
    from . import multiarray
  File "D:\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 14, in <m
odule>
    from . import overrides
  File "D:\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <mod
ule>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nb_author_id.py", line 16, in <module>
    from email_preprocess import preprocess
  File "../tools\email_preprocess.py", line 5, in <module>
    import numpy
  File "D:\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>

    from . import core
  File "D:\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 47, in <mod
ule>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "D:\Anaconda3\python.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed: Das angegebene Modul wurde nicht gefunden.

**Comment by MedAmr** [comment]
i found the issue for the most errors and importerror dll file:
it is the scipy module, you have to uninstall it then install it.

pip uninstall scipy

pip install scipy (newer version)
