### ISSUE TITLE
cannot run the script nb_author_id.py

### ISSUE THREAD

**Issue by Dilylam** [udacity/ud120-projects#333]
Hello everyone,

I am running the script nb_author_id.py from the "naive_bayes" folder and I am using python 2.7.9
It doesnt work. I get this error. 

D:\ML_udacity\ud120-projects\naive_bayes>python nb_author_id.py
Traceback (most recent call last):
  File "nb_author_id.py", line 16, in <module>
    from email_preprocess import preprocess
  File "../tools/email_preprocess.py", line 3, in <module>
    import joblib
  File "C:\Python27\lib\site-packages\joblib\__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "C:\Python27\lib\site-packages\joblib\memory.py", line 271
    raise new_exc from exc
                     ^
SyntaxError: invalid syntax

Can someone please help me how I can solve this? In Pycharm nb_author_id.py does not work either, I have this error "Unresolved reference email_preprocess".

Thanks in advance.

**Comment by styles3544** [comment]
Same for me
