### ISSUE TITLE
Issues with pickle file!!

### ISSUE THREAD

**Issue by Cyborg-07** [udacity/ud120-projects#358]
The following error is being thrown while running nb_author_id, svm_author_id etc. The problem seems to be in pickle file. I am not able to find any solution as of now. Any help is appreciated.

D:\MyGIT\ud120-projects\venv\Scripts\python.exe D:\MyGIT\ud120-projects\svm\svm_author_id.py 
Traceback (most recent call last):
  File "D:\MyGIT\ud120-projects\svm\svm_author_id.py", line 20, in <module>
    features_train, features_test, labels_train, labels_test = preprocess()
  File "../tools/email_preprocess.py", line 35, in preprocess
    word_data = joblib.load(words_file_handler)
  File "D:\MyGIT\ud120-projects\venv\lib\site-packages\joblib\numpy_pickle.py", line 595, in load
    obj = _unpickle(fobj)
  File "D:\MyGIT\ud120-projects\venv\lib\site-packages\joblib\numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle

Process finished with exit code 1

**Comment by gramdharey** [comment]
> 

Have you been able to resolve the issue?

**Comment by devkilly** [comment]
Looks like the code base was updated to use python3, but the course still tells you to use python2.7
Run with python 3, it solved this issue for me. You may need to go back and install requirements on python3, the readme on this git page tells you how.
