### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by er3456qi** [udacity/ud120-projects#46]
I am used to using Python 3,  and I found the code support Python 2 only. So Is there any reason to have to use python 2?

**Comment by kadnan** [comment]
@er3456qi  So what kind of errors are you getting other than `print` statements? `scikit-learn` is also available for Python3

**Comment by Irvel** [comment]
Importing python 2 pickles to python 3 causes errors

**Comment by kadnan** [comment]
Almost all ML related modules available for v3. Which package are you trying to install?

**Comment by ruramos** [comment]
pickle is a native library in python3.5. 
https://docs.python.org/3/library/pickle.html.

**Comment by brylie** [comment]
I am getting print errors on the Naive Bayes lesson. That would be a reasonable place to start.

**Comment by brylie** [comment]
I commented out the print lines in `email_preprocess.py`, and ran the script again. This time I get a cPickle error:

```py

ImportError: No module named 'cPickle'
```

**Comment by brylie** [comment]
I commented out the `import cpickle` line in *email_preprocess.py*, and ran the script again. This time, I get the following error:

```py

  File "../tools/email_preprocess.py", line 33, in preprocess
    authors = pickle.load(authors_file_handler)

TypeError: a bytes-like object is required, not 'str'
```

**Comment by steffanj** [comment]
I followed the same reasoning, changed cPickle for pickle, and also got the TypeError. What I was able to grasp from other online sources is that pickled streams are not always compatible between Python 2 and Python 3. 

I ended up with this workaround:
1. Preprocess (pickle.load) the features and labels on a Python 2 machine. If you are wary about mixing up different Python systems on your machine or don't know how to do that, you could use a different (virtual) machine. I'm on Windows 10 and installed Python 2 on the Windows Subsystem for Linux and it worked great
2. Save the generated variables into a .npz file on your harddrive using numpy.savez. To be on the safe side you can set the flag allow_pickle = False to prevent numpy.savez from relying on pickle, but on my machine it also worked without this flag
3. Instead of doing the preprocessing in Python 3, load this .npz file and map the variables to the correct variable names
4. You're now set and can continue with the rest of your script

You could use the following code
_For the Python 2 part:_
```
#!/usr/bin/python
import sys
sys.path.append("../tools/")
from email_preprocess import preprocess
import numpy

# Preprocess the features and lables
features_train, features_test, labels_train, labels_test = preprocess()
# Save to a file preprocessed.npz in your script directory
numpy.savez("preprocessed", features_train=features_train, features_test=features_test, labels_train=labels_train, labels_test=labels_test, allow_pickle=False)
```

_For the Python 3 part:_
```
#!/usr/bin/python
import numpy

# Load the variables from .npz file. Provide the path to the file
preprocessed = numpy.load("C:/Path/To/Your/File.npz")
# Create (global) variables from the loaded npz-file and assign names to them
for ii in preprocessed:
    globals()[ii] = preprocessed[ii]
# Delete the 'preprocessed' file since it's no longer needed
del preprocessed

# You can continue with the rest of your code here
```

This seemed to do the trick for me. It's a bit of a hassle, I almost gave up on the course because of it, but so far I'm glad I continued because the course seems to be worth it!

**Comment by kynan** [comment]
@steffanj [Anaconda](https://www.continuum.io/anaconda-overview) allows running multiple Python versions in isolated environments (even on Windows).

**Comment by TylerWW** [comment]
I am currently completing the course in Python 3. See [my pull request](https://github.com/udacity/ud120-projects/pull/71) for updated files that are compatible with 3. Right now it makes the project compatible up to the end of the first mini project (naive bayes).

**Comment by andrewgntm** [comment]
@TylerWW - I tried your version of email_preprocess.py but receive this error instead:

  File "../tools\email_preprocess.py", line 36, in preprocess
    word_data = pickle.load(words_file_handler, fix_imports=True)

UnpicklingError: the STRING opcode argument must be quoted

Any idea how to fix this?

**Comment by TylerWW** [comment]
@andrewgntm  Hmm no I'm sorry, the error I was receiving prior to the changes was the one referenced above by @brylie : 
"TypeError: a bytes-like object is required, not 'str'"

I ran the version I posted successfully on python 3.5.2.

**Comment by monkshow92** [comment]
Hi!
I had the same problem.
The pickle file has to be using Unix new lines otherwise at least Python 3.4's C pickle parser fails with exception: pickle.UnpicklingError: the STRING opcode argument must be quoted
I think that some git versions may be changing the Unix new lines ('\n') to DOS lines ('\r\n').

You may use this code to change "word_data.pkl" to "word_data_unix.pkl" and then use the new .pkl file on the script "nb_author_id.py":
[dos2unix.txt](https://github.com/udacity/ud120-projects/files/740034/dos2unix.txt)

`#!/usr/bin/env python
"""\
convert dos linefeeds (crlf) to unix (lf)
usage: dos2unix.py <input> <output>
"""
original = "word_data.pkl"
destination = "word_data_unix.pkl"

content = ''
outsize = 0
with open(original, 'rb') as infile:
  content = infile.read()
with open(destination, 'wb') as output:
  for line in content.splitlines():
    outsize += len(line) + 1
    output.write(line + str.encode('\n'))

print("Done. Saved %s bytes." % (len(content)-outsize))`

dos2unix.py addapted from:
[http://stackoverflow.com/a/19702943](url)

**Comment by Yumlembam** [comment]
@monkshow92  thank you it works

**Comment by monkshow92** [comment]
you are welcome @Yumlembam !

**Comment by zuoshou0929** [comment]
@er3456qi  @Irvel @brylie @andrewgntm @TylerWW I have made this project using Python3,and finished some other projects from ud036 and ud170 , it's easy to understand, you could fork my git:[Python3学习](https://github.com/zuoshou0929/python3_learn)

1. About the issue of **pickle** and **cPickle**, you needn't  import cPickle,use pickle only is ok, and make 
-`authors_file_handler = open(authors_file, "rb")`
-`words_file_handler = open(words_file, "rb")`
-`word_data = pickle.load(words_file_handler)`

2. About the **print** statement, you should change all the print statement to be **print()**

**Comment by renesillo2** [comment]
Hi,

I got around this by installing Anaconda 2 AND Anaconda 3 on my PC. Then, I started a project in PyCharm IDE and set the python interpreter to be the python.exe in Anaconda2. This way you can have both installs without having to change the code. 

I ran startup.py and it worked after doing the above steps.

all software here is free.

**Comment by vishnoiprem** [comment]
Hi Please help me , i changed open(authors_file, "rb") but stilll  i am getting same error
features_train, features_test, labels_train, labels_test = preprocess()


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-ac88a4c5f984> in <module>()
----> 1 features_train, features_test, labels_train, labels_test = preprocess()
      2 

/Users/vishnoiprem/Udemy/udacity/ud120-projects/tools/email_preprocess.py in preprocess(words_file, authors_file)
     31     # this preprocessing will be repeated in the text learning mini-project
     32     print('authors_file_handler',authors_file)
---> 33 
     34     authors_file_handler = open(authors_file, "rb")
     35     print('authors_file_handler',authors_file_handler)

TypeError: a bytes-like object is required, not 'str'

**Comment by burhanshakir** [comment]
@monkshow92  Where should I input that code ? Its not working when I put it in email_preprocesses.py

**Comment by mrplane** [comment]
@monkshow92 

Your dos2unix fix is brilliant! Now I can get on with actual machine learning.
Thanks!!

**Comment by monkshow92** [comment]
You are welcome @mrplane, I'm glad to help! :)

**Comment by fmaletski** [comment]
Thanks @monkshow92 ! Helped me too!

**Comment by AyushRohatgi** [comment]
You can create virtual environments using anaconda to run python2 and python3 codes
https://conda.io/docs/py2or3.html

**Comment by KordianD** [comment]
Genius solution @monkshow92, helped me a lot!

**Comment by Ipgnosis** [comment]
Awesome @monkshow92...problem solved, thx2u!

@brylie @steffanj the cPickle problem is caused by a name change on Python3 from cPickle to _pickle.
Just change line 4 of email_preprocess.py to: "import _pickle as cPickle"

**Comment by brylie** [comment]
@Ipgnosis thanks for the recommendation. That should probably be part of this pull request :-)

**Comment by ArtyomKaltovich** [comment]
@Ipgnosis @brylie @steffan
>Just change line 4 of email_preprocess.py to: "import _pickle as cPickle"

that is not enough, you should read file in binary format, you can see how to do it in my pull request mentioned before, or in my own [repository](https://github.com/ArtyomKaltovich/ud120-projects/blob/master/tools/email_preprocess.py).

**Comment by steewieg** [comment]
monkshow92 great fix!
I was not able to fix that with several workarounds.
I almost gave the course...

But your fix helped me!

Thanks.

**Comment by RoshanADK** [comment]
monkshow92 , Take a Bow ! :) 
You owe me one ! 
Thanks man !

**Comment by mrca** [comment]
@monkshow92 thanks for the code. BTW it is also possible to change the line endings directly in a text editor such as Notepad++ or Atom.

**Comment by zhililab** [comment]
@monkshow92 It works well. Thx ;)

**Comment by monkshow92** [comment]
you are welcome guys! 
It's nice to know I could help you solve this issue, which made me struggle in the same way!
@fmaletski , @KordianD , @Ipgnosis , @steewieg , @RoshanADK , @mrca , @zhililab

**Comment by johnmisquita** [comment]
@leftthomas  has a good solution to the problem; also change the she-bang at the start of the code from #!/usr/bin/python to #!/usr/bin/python3 if you have installed your modules like sklearn for python 3

**Comment by mayanksharma1992** [comment]
@monkshow92 Thanks for the solution

**Comment by LaloCo** [comment]
@monkshow92 you saved me with that dos2unix file! Thanks a lot!

**Comment by Vaibhav1671998** [comment]
@leftthomas How to run the code after writing the classifier ? 
It's giving the error 
_pickle.UnpicklingError: the STRING opcode argument must be quoted

Plzz help

**Comment by Vaibhav1671998** [comment]
@leftthomas @monkshow92 I am getting 0.92 accuracy . 
But Udacity is expecting higher how to resove that if u can help ?

**Comment by stawary** [comment]
@monkshow92 Thanks a lot ! It has taken me a lot of time to fix , until I see your solution.

**Comment by davis-9fv** [comment]
@monkshow92  you are the best!

**Comment by bdushimi** [comment]
I have been able to read the file but I only got zeros in both features_test and features_train. Please take a look on the attached picture.
![error](https://user-images.githubusercontent.com/35345818/37323313-8f9de88a-268b-11e8-9868-c3210db48752.JPG)

**Comment by srikanthgr1** [comment]
@monkshow92 
you dos2unix file saved me from lot of frustations ! Thanks a lot!

**Comment by Ian-Dzindo01** [comment]
https://github.com/flyinactor91/ud120-projects

This is the link to all of the course material, translated into Python 3!

**Comment by SpecialNightz** [comment]
Not sure if anyone has a solution, but I used @steffanj Solution to get through the Naïve bayes part with the Enron dataset, but now I'm stuck on lesson 6 where we have to work with the Enron dataset again. I have problems loading the Enron dataset and I get the Picke UnpicklingError: (enron_data = pickle.load(open("../../resources/enron/enron_dataset.pkl", "rb"))
_pickle.UnpicklingError: the STRING opcode argument must be quoted) 

So far I've tried running other's people solutions like the github solutions from flyinactor91 and leftthomas but it keeps giving me the same error. 
Does anyone have a fix for this?

**Comment by mrca** [comment]
@SpecialNightz check out the comment of @monkshow92 above. You need to change the line endings to DOS: 
monkshow92 commented on Jan 30 2017

**Comment by SpecialNightz** [comment]
@mrca  Thanks, that fixed it for me! I think I might have even used his script to get through the Naïve bayes part to load the other pkl file, but anyways thanks for the help man!

**Comment by trenton3983** [comment]
Thanks for the resolution to this issue.  The better question is why UDACITY hasn't updated this code to use modern Python and is instead using legacy python.

**Comment by monkshow92** [comment]
@mayanksharma1992 , @LaloCo , @stawary , @davis-9fv , @srikanthgr1 
you're welcome guys! Glad to help!

**Comment by SpecialNightz** [comment]
@monkshow92 Do you have a solution to load the emails into lesson 11 with the text learning part aswell?
I'm stuck at the vectorize_text part, and I've downloaded the dataset as tar file and as npz file but cant seem to get it to load..

**Comment by dakkshnand** [comment]
@monkshow92 I don't understand do I copy the code from the .txt file in my nb_author_id file?

**Comment by RhythmGilhotra** [comment]
These are the solution to the errors that i've come across in "naive bayes" till now
(a) In **python3.x** cPickle has changed from **cPickle to _pickle**. Thus in python3.x, you can do the following if you want to use cPickle:
`import _pickle as cPickle`

(b)The print function in python3.x requires the code to be enclosed in () which wasn't required in python2.x 

(c)  **TypeError: a bytes-like object is required, not 'str'**
This error can be resolved by opening the file in binary readable format.
In the email_preprocess.py change the code by these lines of codes in their respective line numbers.
Line 32 : `authors_file_handler = open(authors_file, "rb")`
Line 36: `    words_file_handler = open(words_file, "rb")`

**Comment by nit-esh** [comment]
Hi,
I' getting error as:
pickle.UnpicklingError: the STRING opcode argument must be quoted

Help!

**Comment by ozererdogan** [comment]
> Hi!
> I had the same problem.
> The pickle file has to be using Unix new lines otherwise at least Python 3.4's C pickle parser fails with exception: pickle.UnpicklingError: the STRING opcode argument must be quoted
> I think that some git versions may be changing the Unix new lines ('\n') to DOS lines ('\r\n').
> 
> You may use this code to change "word_data.pkl" to "word_data_unix.pkl" and then use the new .pkl file on the script "nb_author_id.py":
> [dos2unix.txt](https://github.com/udacity/ud120-projects/files/740034/dos2unix.txt)
> 
> `#!/usr/bin/env python
> """
> convert dos linefeeds (crlf) to unix (lf)
> usage: dos2unix.py 
> """
> original = "word_data.pkl"
> destination = "word_data_unix.pkl"
> 
> content = ''
> outsize = 0
> with open(original, 'rb') as infile:
> content = infile.read()
> with open(destination, 'wb') as output:
> for line in content.splitlines():
> outsize += len(line) + 1
> output.write(line + str.encode('\n'))
> 
> print("Done. Saved %s bytes." % (len(content)-outsize))`
> 
> dos2unix.py addapted from:
> [http://stackoverflow.com/a/19702943](url)

Thanks for solving the issue, it worked for me too!

**Comment by JamaicanFriedChicken** [comment]
> @mrca Thanks, that fixed it for me! I think I might have even used his script to get through the Naïve bayes part to load the other pkl file, but anyways thanks for the help man!

Can I ask what was it that you did for the enron dataset?I am having the exact trouble you have encountered but I can't seem to solve it

**Comment by wafa-b** [comment]
Thanks @RhythmGilhotra , your solution works fine with me with python3, 
I also faced this  error :
**Traceback (most recent call last):
  File "nb_author_id.py", line 23, in <module>
    features_train, features_test, labels_train, labels_test = preprocess()
  File "../tools/email_preprocess.py", line 44, in preprocess
    features_train, features_test, labels_train, labels_test = cross_validation.train_test_split(word_data, authors, test_size=0.1, random_state=42)
NameError: name 'cross_validation' is not defined**
I solved by:
1) Remove **Line 7**  from sklearn import cross_validation.
2) Change **Line 42** to     ### features_train, features_test, labels_train, labels_test = train_test_split(word_data, authors, test_size=0.1, random_state=42)

**Comment by bryanekong** [comment]
> 

I'm sorry this is a little confusing, where should i save this new docs2unix file?
