### ISSUE TITLE
ImportError: No module named numpy

### ISSUE THREAD

**Issue by HarshaNalluru** [udacity/ud120-projects#67]
(Lesson1-MINI PROJECT)
On running this command   `python nb_author_id.py ` from `naive_bayes` folder

Got this error
> Traceback (most recent call last):
>   File "nb_author_id.py", line 16, in <module>
>     from email_preprocess import preprocess
>   File "../tools/email_preprocess.py", line 5, in <module>
>     import numpy
> ImportError: No module named numpy
> 

Please help!!

**Comment by ShengKungYi** [comment]
There are certain Python packages necessary to run and perform the code for the course; `numpy` is one of them. Have you tried running the `startup.py` script in the "tools" folder? If not, then you should make sure to run it to check if you have all packages installed and to get the Enron e-mail corpus, which will be referred to and used later in the course.

**Comment by jeffveleze** [comment]
I have installed numpy as it's shown:

Jeffersons-MacBook-Pro:~ jeffveleze$ pip install numpy
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python

But still getting this error :( 

Jeffersons-MacBook-Pro:naive_bayes jeffveleze$ python nb_author_id.py
Traceback (most recent call last):
  File "nb_author_id.py", line 17, in <module>
    from email_preprocess import preprocess
  File "../tools/email_preprocess.py", line 5, in <module>
    import numpy
ImportError: No module named numpy

What might be happen?

Thanks in advance!

**Comment by workpioupiou** [comment]
Hello, 

I'm not an expert but when I had installed my Debian, I had a python by default. I installed after that for a personal project, python3. 
I discovered that my "pip install" command was installing my libraries on python3 folder like if pip was pip3. 
For resolved my problem, I had installed python2.7 (with apt-get install) and all run normally (you need to reinstall the library like scikit-learn and nltk. 
Best regards

**Comment by johnmisquita** [comment]
which python are you using? if you have installed numpy on python 3 then change the #!/usr/bin/python to #!/usr/bin/python3 at the beginning of your code else install numpy for python 2
