### ISSUE TITLE
Error python startup.py link is broken

### ISSUE THREAD

**Issue by jersonjunior** [udacity/ud120-projects#84]
python startup.py

checking for nltk
you should install nltk before continuing
checking for numpy
you should install numpy before continuing
checking for scipy
you should install scipy before continuing
checking for sklearn
you should install sklearn before continuing

downloading the Enron dataset (this may take a while)
to check on progress, you can cd up one level, then execute <ls -lthr>
Enron dataset should be last item on the list, along with its current size
download will complete at about 423 MB
Traceback (most recent call last):
  File "startup.py", line 35, in <module>
    urllib.urlretrieve(url, filename="../enron_mail_20150507.tgz")
  File "/usr/lib64/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib64/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib64/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1227, in connect
    HTTPConnection.connect(self)
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known

**Comment by javierlmendez** [comment]
I'm having the same issue. I'm running python 2.7 inside conda.
